import type {
  ModuleWithProgress,
  LessonWithStatus,
  Technique,
  QuizQuestion,
} from "@/lib/types";

export const DEMO_MODULES: ModuleWithProgress[] = [
  {
    id: "stances",
    title_en: "Stances",
    title_zh: "步型",
    title_pinyin: "Bùxíng",
    category: "Foundation",
    description:
      "Master the five essential Wushu stances. Every technique in Wushu is built on these foundations.",
    sort_order: 1,
    completedCount: 0,
    totalCount: 3,
    unlocked: true,
    lessons: [],
  },
  {
    id: "hand-forms",
    title_en: "Hand Forms",
    title_zh: "手型",
    title_pinyin: "Shǒuxíng",
    category: "Foundation",
    description:
      "Fist, palm, and hook — the three fundamental hand shapes that define Wushu striking.",
    sort_order: 2,
    completedCount: 0,
    totalCount: 1,
    unlocked: true,
    lessons: [],
  },
  {
    id: "punches",
    title_en: "Punch Techniques",
    title_zh: "拳法",
    title_pinyin: "Quánfǎ",
    category: "Foundation",
    description:
      "Straight, swinging, push, and chop — core strikes powered by waist rotation.",
    sort_order: 3,
    completedCount: 0,
    totalCount: 2,
    unlocked: true,
    lessons: [],
  },
  {
    id: "kicks",
    title_en: "Kick Techniques",
    title_zh: "腿法",
    title_pinyin: "Tuǐfǎ",
    category: "Foundation",
    description:
      "Front, side, crescent, snap, and thrust kicks — the full basic kick toolkit.",
    sort_order: 4,
    completedCount: 0,
    totalCount: 3,
    unlocked: true,
    lessons: [],
  },
  {
    id: "balance",
    title_en: "Balance",
    title_zh: "平衡",
    title_pinyin: "Pínghéng",
    category: "Foundation",
    description:
      "Hold your center while standing on one leg — the basis of all static beauty in Wushu.",
    sort_order: 5,
    completedCount: 0,
    totalCount: 1,
    unlocked: true,
    lessons: [],
  },
  {
    id: "conditioning",
    title_en: "Conditioning",
    title_zh: "素质训练",
    title_pinyin: "Sùzhì Xùnliàn",
    category: "Foundation",
    description:
      "Flexibility and strength work — the daily training that unlocks every other skill.",
    sort_order: 6,
    completedCount: 0,
    totalCount: 1,
    unlocked: true,
    lessons: [],
  },
  // ─── Forms ────────────────────────────────────────────────────────────────
  {
    id: "five-stance-form",
    title_en: "Five Stance Form",
    title_zh: "五步拳",
    title_pinyin: "Wǔ Bù Quán",
    category: "Forms",
    description:
      "The first complete form every wushu student learns. Combines all 5 basic stances with basic hand techniques in one short routine. The bridge between isolated basics and real forms.",
    sort_order: 7,
    completedCount: 0,
    totalCount: 1,
    unlocked: true,
    lessons: [],
  },
  {
    id: "elementary-long-fist",
    title_en: "Elementary Long Fist",
    title_zh: "初级长拳",
    title_pinyin: "Chūjí Chángquán",
    category: "Forms",
    description:
      "The foundational changquan series — three progressively harder routines. Yi Lu focuses on basic combos, San Lu adds jumps and faster transitions.",
    sort_order: 8,
    completedCount: 0,
    totalCount: 3,
    unlocked: true,
    lessons: [],
  },
  {
    id: "style-routines",
    title_en: "Style Routines",
    title_zh: "风格套路",
    title_pinyin: "Fēnggé Tàolù",
    category: "Forms",
    description:
      "Branch into southern style or tai chi — different energy and philosophy from changquan.",
    sort_order: 9,
    completedCount: 0,
    totalCount: 2,
    unlocked: true,
    lessons: [],
  },
  {
    id: "weapon-routines",
    title_en: "Weapon Routines",
    title_zh: "器械套路",
    title_pinyin: "Qìxiè Tàolù",
    category: "Forms",
    description:
      "The four traditional weapons — broadsword, straight sword, spear, and staff. Each has unique characteristics and techniques.",
    sort_order: 10,
    completedCount: 0,
    totalCount: 4,
    unlocked: true,
    lessons: [],
  },
];

export const DEMO_LESSONS: Record<string, LessonWithStatus[]> = {
  stances: [
    {
      id: "horse-bow-stance",
      module_id: "stances",
      title_en: "Horse & Bow Stance",
      title_zh: "马步 & 弓步",
      title_pinyin: "Mǎbù & Gōngbù",
      description:
        "The two most fundamental stances — the base of all Wushu power generation.",
      sort_order: 1,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
    {
      id: "empty-crouch-stance",
      module_id: "stances",
      title_en: "Empty & Crouch Stance",
      title_zh: "虚步 & 仆步",
      title_pinyin: "Xūbù & Pūbù",
      description:
        "Defensive stances used in transitions and retreating techniques.",
      sort_order: 2,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
    {
      id: "cross-stance",
      module_id: "stances",
      title_en: "Cross Stance",
      title_zh: "歇步",
      title_pinyin: "Xiēbù",
      description:
        "A deep crossed-leg stance used in acrobatic transitions and low sweeping movements.",
      sort_order: 3,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
  ],
  "hand-forms": [
    {
      id: "fist-palm-hook",
      module_id: "hand-forms",
      title_en: "Fist · Palm · Hook",
      title_zh: "拳 · 掌 · 勾",
      title_pinyin: "Quán · Zhǎng · Gōu",
      description:
        "The three hand shapes every Wushu practitioner must know cold.",
      sort_order: 1,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
  ],
  punches: [
    {
      id: "straight-swing-punch",
      module_id: "punches",
      title_en: "Straight & Swinging Punch",
      title_zh: "冲拳 & 贯拳",
      title_pinyin: "Chōngquán & Guànquán",
      description:
        "The fundamental straight thrust and the wide-arcing swing to the temple.",
      sort_order: 1,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
    {
      id: "push-chop-palm",
      module_id: "punches",
      title_en: "Push & Chop Palm",
      title_zh: "推掌 & 劈掌",
      title_pinyin: "Tuīzhǎng & Pīzhǎng",
      description:
        "Open-hand strikes — one pushing forward, one splitting downward.",
      sort_order: 2,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
  ],
  kicks: [
    {
      id: "front-side-kick",
      module_id: "kicks",
      title_en: "Front & Side Kick",
      title_zh: "正踢腿 & 侧踢腿",
      title_pinyin: "Zhèngtī tuǐ & Cètī tuǐ",
      description:
        "Signature straight-leg basic kicks — reach the forehead, slap the foot.",
      sort_order: 1,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
    {
      id: "crescent-kicks",
      module_id: "kicks",
      title_en: "Outward & Inward Crescent",
      title_zh: "外摆腿 & 里合腿",
      title_pinyin: "Wàibǎi tuǐ & Lǐhé tuǐ",
      description:
        "Arcing crescent kicks — inside to outside, and outside to inside.",
      sort_order: 2,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
    {
      id: "snap-thrust-kick",
      module_id: "kicks",
      title_en: "Snap & Thrust Kick",
      title_zh: "弹腿 & 蹬腿",
      title_pinyin: "Tántuǐ & Dēngtuǐ",
      description:
        "Chambered kicks — snap out with the instep, or drive through with the heel.",
      sort_order: 3,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
  ],
  balance: [
    {
      id: "knee-swallow-balance",
      module_id: "balance",
      title_en: "Knee Lift & Swallow Balance",
      title_zh: "提膝平衡 & 燕式平衡",
      title_pinyin: "Tíxī pínghéng & Yànshì pínghéng",
      description:
        "Two foundational one-leg balance postures used throughout traditional forms.",
      sort_order: 1,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
  ],
  conditioning: [
    {
      id: "flexibility-foundations",
      module_id: "conditioning",
      title_en: "Flexibility Foundations",
      title_zh: "柔韧",
      title_pinyin: "Róurèn",
      description:
        "Daily leg stretches and splits — the long road to high kicks.",
      sort_order: 1,
      chinese_level: 1,
      derivedStatus: "available",
      quiz_score: null,
      quiz_attempts: 0,
    },
  ],
  // ─── Forms ────────────────────────────────────────────────────────────────
  "five-stance-form": [
    {
      id: "wubuquan",
      module_id: "five-stance-form",
      title_en: "Five Stance Form",
      title_zh: "五步拳",
      title_pinyin: "Wǔ Bù Quán",
      description:
        "A short routine linking all five basic stances — horse, bow, empty, crouch, and cross — with punches, palm strikes, and a kick. Every movement flows from stance to stance.",
      sort_order: 1,
      chinese_level: 2,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete all Basics modules to unlock",
    },
  ],
  "elementary-long-fist": [
    {
      id: "changquan-yi-lu",
      module_id: "elementary-long-fist",
      title_en: "First Road",
      title_zh: "一路",
      title_pinyin: "Yī Lù",
      description:
        "The entry point to changquan forms. Straight-line combinations of stances, punches, and kicks performed with speed and extension.",
      sort_order: 1,
      chinese_level: 2,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete 五步拳 · Five Stance Form to unlock",
    },
    {
      id: "changquan-er-lu",
      module_id: "elementary-long-fist",
      title_en: "Second Road",
      title_zh: "二路",
      title_pinyin: "Èr Lù",
      description:
        "Builds on First Road with more complex combinations, direction changes, and increased tempo.",
      sort_order: 2,
      chinese_level: 3,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete 一路 · First Road first",
    },
    {
      id: "changquan-san-lu",
      module_id: "elementary-long-fist",
      title_en: "Third Road",
      title_zh: "三路",
      title_pinyin: "Sān Lù",
      description:
        "The most demanding of the three roads — introduces jumping kicks, aerial transitions, and full-speed combinations.",
      sort_order: 3,
      chinese_level: 4,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete 二路 · Second Road first",
    },
  ],
  "style-routines": [
    {
      id: "elementary-nanquan",
      module_id: "style-routines",
      title_en: "Elementary Southern Fist",
      title_zh: "初级南拳",
      title_pinyin: "Chūjí Nánquán",
      description:
        "Southern fist is compact, powerful, and grounded — short bridges, strong stances, and explosive bursts of power. A striking contrast to the long-range flow of changquan.",
      sort_order: 1,
      chinese_level: 3,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete Elementary Long Fist to unlock",
    },
    {
      id: "elementary-taijiquan",
      module_id: "style-routines",
      title_en: "Elementary Tai Chi",
      title_zh: "初级太极拳",
      title_pinyin: "Chūjí Tàijíquán",
      description:
        "Slow, continuous, circular movement — the opposite philosophy to changquan. Develops internal connection, relaxation, and the ability to redirect force.",
      sort_order: 2,
      chinese_level: 3,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete 初级南拳 · Elementary Southern Fist first",
    },
  ],
  "weapon-routines": [
    {
      id: "elementary-daoshu",
      module_id: "weapon-routines",
      title_en: "Elementary Broadsword",
      title_zh: "初级刀术",
      title_pinyin: "Chūjí Dāoshù",
      description:
        "The broadsword (dāo) is fast, fierce, and one-edged. Elementary routines cover the eight basic cuts, blocks, and the characteristic flowing transitions.",
      sort_order: 1,
      chinese_level: 3,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete at least one Style Routine to unlock",
    },
    {
      id: "elementary-jianshu",
      module_id: "weapon-routines",
      title_en: "Elementary Straight Sword",
      title_zh: "初级剑术",
      title_pinyin: "Chūjí Jiànshù",
      description:
        "The straight sword (jiàn) is elegant and precise — double-edged, lighter, and requiring a high degree of control and finger dexterity for the sword fingers.",
      sort_order: 2,
      chinese_level: 3,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete 初级刀术 · Elementary Broadsword first",
    },
    {
      id: "elementary-qiangshu",
      module_id: "weapon-routines",
      title_en: "Elementary Spear",
      title_zh: "初级枪术",
      title_pinyin: "Chūjí Qiāngshù",
      description:
        "The spear (qiāng) demands full-body coordination — thrusts, parries, and sweeps powered by waist rotation, with the tip controlled to a precise point.",
      sort_order: 3,
      chinese_level: 4,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete 初级剑术 · Elementary Straight Sword first",
    },
    {
      id: "elementary-gunshu",
      module_id: "weapon-routines",
      title_en: "Elementary Staff",
      title_zh: "初级棍术",
      title_pinyin: "Chūjí Gùnshù",
      description:
        "The staff (gùn) is the longest and most physically demanding of the four — sweeping strikes, spins, and vertical drops that require full-body strength and coordination.",
      sort_order: 4,
      chinese_level: 4,
      derivedStatus: "locked",
      quiz_score: null,
      quiz_attempts: 0,
      prerequisite_label: "Complete 初级枪术 · Elementary Spear first",
    },
  ],
};

export const DEMO_TECHNIQUES: Record<string, Technique[]> = {
  // ─── Forms ────────────────────────────────────────────────────────────────
  // 五步拳 — Five-Step Fist. 9 sequential movements; 6 scored via stance_ref.
  wubuquan: [
    {
      id: "wubuquan-m1-ready",
      lesson_id: "wubuquan",
      english: "Ready Stance",
      chinese: "预备式",
      pinyin: "Yùbèi Shì",
      description:
        "Stand tall with feet together, arms relaxed at your sides. Eyes forward, chin level. Breathe in and settle your mind before beginning the form.",
      key_points: [
        "Feet together, heels touching",
        "Arms hang naturally at the sides",
        "Spine tall, shoulders relaxed",
        "Eyes forward on an imaginary opponent",
      ],
      common_mistakes: [
        "Shoulders hunched or tense",
        "Eyes down — break your focus before the form starts",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: null,
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m2-gongbu-chongquan",
      lesson_id: "wubuquan",
      english: "Cross-Step Bow Stance Punch",
      chinese: "拗步冲拳",
      pinyin: "Àobù Chōngquán",
      description:
        "Step forward into a deep bow stance and drive a straight punch from the rear hand (cross-side). The punch explodes with the hip rotation.",
      key_points: [
        "Front knee bent to 90°, directly over the ankle",
        "Back leg fully extended, foot angled ~45°",
        "Punch rotates from vertical to horizontal at full extension",
        "Hips square to the front",
      ],
      common_mistakes: [
        "Front knee collapsing inward or past the toes",
        "Rear foot lifting off the ground",
        "Punching with the arm alone — no hip drive",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: "bow-stance",
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m3-tantui-chongquan",
      lesson_id: "wubuquan",
      english: "Snap Kick with Punch",
      chinese: "弹腿冲拳",
      pinyin: "Tántuǐ Chōngquán",
      description:
        "Snap the rear leg forward in a straight-leg kick (tántuǐ) while simultaneously delivering a punch on the same side. Land in bow stance.",
      key_points: [
        "Kicking leg whips from the knee — toes snap to a point",
        "Kick travels horizontally at waist height",
        "Punch fires at the moment of kick extension",
        "Land balanced — no stumble",
      ],
      common_mistakes: [
        "Lifting the knee up instead of snapping from the knee",
        "Kicking with a floppy foot — toes must be tensed",
        "Punch and kick out of sync",
      ],
      sort_order: 3,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: "bow-stance",
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m4-mabu-jiada",
      lesson_id: "wubuquan",
      english: "Horse Stance Block-Punch",
      chinese: "马步架打",
      pinyin: "Mǎbù Jiàdǎ",
      description:
        "Drop into horse stance. One fist rises overhead in a rising block (jià) while the other drives a horizontal punch at the opposite side.",
      key_points: [
        "Feet 2× shoulder-width apart, thighs parallel to the floor",
        "Back straight, weight evenly distributed",
        "Rising block arm bent overhead, forearm horizontal",
        "Punching arm fully extended at shoulder height",
      ],
      common_mistakes: [
        "Stance too narrow or too shallow",
        "Leaning torso to counterbalance the punch",
        "Blocking arm too low — must protect the head",
      ],
      sort_order: 4,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: "horse-stance",
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m5-xiebu-gaida",
      lesson_id: "wubuquan",
      english: "Rest Stance Covering Strike",
      chinese: "歇步盖打",
      pinyin: "Xiēbù Gàidǎ",
      description:
        "Cross the legs into a deep rest stance while swinging a downward covering strike (gài) across the body. Compact and powerful.",
      key_points: [
        "Legs crossed, back heel lifted, front foot flat",
        "Sink until back knee hovers near the ground",
        "Strike arcs from high to low across the centerline",
        "Torso remains upright despite the deep squat",
      ],
      common_mistakes: [
        "Not sinking deep enough — back knee still high",
        "Losing balance mid-cross",
        "Striking with arm only — need waist rotation",
      ],
      sort_order: 5,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: "rest-stance",
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m6-tixi-chuanzhang",
      lesson_id: "wubuquan",
      english: "Knee-Lift Palm Thrust",
      chinese: "提膝穿掌",
      pinyin: "Tíxī Chuānzhǎng",
      description:
        "Rise out of the rest stance, lifting one knee high while thrusting a spear palm (chuānzhǎng) forward. A transitional movement setting up the crouch stance.",
      key_points: [
        "Raised thigh parallel to the floor, toes pointed down",
        "Supporting leg fully extended — do not bend",
        "Palm thrust fingers-first, palm facing down",
        "Balance on one leg without wobble",
      ],
      common_mistakes: [
        "Raised knee below parallel",
        "Supporting leg bent — loses height and power",
        "Palm hand not flat — fingers curled",
      ],
      sort_order: 6,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: null,
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m7-pubu-chuanzhang",
      lesson_id: "wubuquan",
      english: "Crouch Stance Palm Thrust",
      chinese: "仆步穿掌",
      pinyin: "Pūbù Chuānzhǎng",
      description:
        "Drop the lifted leg outward into a deep crouch stance while sending a second palm thrust along the extended leg. A ground-level attacking posture.",
      key_points: [
        "Extended leg fully straight, foot flat",
        "Bent leg thigh below parallel",
        "Palm thrust travels along the extended leg",
        "Torso upright — no caving forward",
      ],
      common_mistakes: [
        "Extended knee bent",
        "Extended foot rolled to the outer edge",
        "Chest collapsing onto the bent thigh",
      ],
      sort_order: 7,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: "crouch-stance",
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m8-xubu-tiaozhang",
      lesson_id: "wubuquan",
      english: "Empty Stance Lifting Palm",
      chinese: "虚步挑掌",
      pinyin: "Xūbù Tiǎozhǎng",
      description:
        "Rise from the crouch into an empty stance with most weight on the back leg, while lifting a palm (tiǎo) upward — an uprooting, deflecting motion.",
      key_points: [
        "~90% weight on rear bent leg",
        "Front foot lightly touches with toes only",
        "Lifting palm rises from waist to shoulder height",
        "Torso upright, chest open",
      ],
      common_mistakes: [
        "Weight still too forward — front foot should feel empty",
        "Leaning back to compensate instead of sitting on the rear leg",
        "Lifting arm too high — shoulder should stay relaxed",
      ],
      sort_order: 8,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: "empty-stance",
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
    {
      id: "wubuquan-m9-closing",
      lesson_id: "wubuquan",
      english: "Closing Salute",
      chinese: "收势",
      pinyin: "Shōu Shì",
      description:
        "Return to feet-together, bring the right fist into the left palm at chest height (拳礼 quánlǐ). The form is complete.",
      key_points: [
        "Feet together, heels touching",
        "Right fist meets left palm at sternum height",
        "Arms form a rounded shape — elbows slightly out",
        "Eyes forward, bow slightly with respect",
      ],
      common_mistakes: [
        "Rushing the salute — it should be deliberate",
        "Hands too low or too high",
      ],
      sort_order: 9,
      video_url: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      reference_angles: null,
      stance_ref: null,
      source: "Standard PE-textbook 五步拳 sequence",
      sourceUrl: "https://www.youtube.com/watch?v=aq4PHYF3XSY",
      attribution: "community",
    },
  ],
  "horse-bow-stance": [
    {
      id: "horse-stance",
      lesson_id: "horse-bow-stance",
      english: "Horse Stance",
      chinese: "马步",
      pinyin: "Mǎbù",
      description:
        "The cornerstone of Wushu training. Feet shoulder-width apart, knees bent at 90°, thighs parallel to the floor. Holds the body low and stable like a rider on horseback.",
      key_points: [
        "Feet are parallel, approximately two shoulder-widths apart",
        "Knees track directly over the toes — never caving inward",
        "Thighs are parallel to the floor at full depth",
        "Back is straight; do not lean forward or let the hips tilt",
        "Weight is distributed evenly between both feet",
      ],
      common_mistakes: [
        "Knees collapsing inward (valgus collapse) — weakens the stance and strains the knee",
        "Rising onto the toes — the whole foot must stay flat on the ground",
        "Leaning the torso forward to compensate for insufficient hip flexibility",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=LiEMQUIPPQg&t=21",
      reference_angles: null,
      source: "Sunny Lai Wushu — Basic Stances Tutorial",
      sourceUrl: "https://www.youtube.com/watch?v=LiEMQUIPPQg",
      attribution: "community",
    },
    {
      id: "bow-stance",
      lesson_id: "horse-bow-stance",
      english: "Bow Stance",
      chinese: "弓步",
      pinyin: "Gōngbù",
      description:
        "The bow stance resembles a drawn bow — front knee bent and loaded, back leg straight and strong. The primary attack stance in Wushu forms.",
      key_points: [
        "Front knee is bent to ~90°, directly above the ankle — never past the toes",
        "Back leg is fully extended with the foot flat and turned out at ~45°",
        "Hips face forward — resist the urge to open the hip toward the back leg",
        "Torso is upright; weight is roughly 70% front, 30% rear",
        "The line from rear heel through hip to crown is straight",
      ],
      common_mistakes: [
        "Front knee sliding past the toes — overloads the patellar tendon",
        "Back foot lifting off the ground — destroys rear-leg drive",
        "Opening the hips sideways instead of keeping them square to the front",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=LiEMQUIPPQg&t=120",
      reference_angles: null,
      source: "Sunny Lai Wushu — Basic Stances Tutorial",
      sourceUrl: "https://www.youtube.com/watch?v=LiEMQUIPPQg",
      attribution: "community",
    },
  ],
  "empty-crouch-stance": [
    {
      id: "empty-stance",
      lesson_id: "empty-crouch-stance",
      english: "Empty Stance",
      chinese: "虚步",
      pinyin: "Xūbù",
      description:
        "Shifts nearly all weight to the rear leg, leaving the front foot 'empty' — lightly touching the ground, ready to kick or step without telegraphing.",
      key_points: [
        "~90% of weight is on the rear bent leg",
        "Front foot touches lightly with the ball of the foot or heel only",
        "Rear knee is bent and tracks over the rear toes",
        "Torso is upright — do not lean backward",
      ],
      common_mistakes: [
        "Too much weight on the front foot — it should feel nearly weightless",
        "Leaning the torso backward instead of keeping the spine vertical",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=LiEMQUIPPQg&t=247",
      reference_angles: null,
      source: "Sunny Lai Wushu — Basic Stances Tutorial",
      sourceUrl: "https://www.youtube.com/watch?v=LiEMQUIPPQg",
      attribution: "community",
    },
    {
      id: "crouch-stance",
      lesson_id: "empty-crouch-stance",
      english: "Crouch Stance",
      chinese: "仆步",
      pinyin: "Pūbù",
      description:
        "An extremely deep lateral stance where one leg extends fully along the ground while the other squats low. Used in sweeping movements and ground-level transitions.",
      key_points: [
        "One leg is fully extended sideways, inner thigh close to the floor",
        "Extended foot is flat — do not let it roll to the outer edge",
        "The squatting leg bears full body weight; thigh below parallel",
        "Torso faces forward — chest does not collapse onto the thigh",
      ],
      common_mistakes: [
        "Extended knee bending — the leg must remain completely straight",
        "Rolling onto the outer edge of the extended foot",
        "Torso caving forward and losing upper-body structure",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=LiEMQUIPPQg&t=334",
      reference_angles: null,
      source: "Sunny Lai Wushu — Basic Stances Tutorial",
      sourceUrl: "https://www.youtube.com/watch?v=LiEMQUIPPQg",
      attribution: "community",
    },
  ],
  "cross-stance": [
    {
      id: "rest-stance",
      lesson_id: "cross-stance",
      english: "Rest / Cross Stance",
      chinese: "歇步",
      pinyin: "Xiēbù",
      description:
        "Both knees are deeply bent with legs crossed. The rear knee rests close to the calf of the front leg. A compact, powerful stance used before explosive jumps and turns.",
      key_points: [
        "Both feet are flat on the ground",
        "Legs are crossed with one foot directly in front of the other",
        "The rear knee lowers toward the ground — aim to hover just above the floor",
        "Torso remains upright; arms vary by technique",
      ],
      common_mistakes: [
        "Rear heel lifting off the ground — both heels must stay down",
        "Sitting too high — the cross position requires a very deep squat",
        "Losing lateral balance — engage the core and press inner knees together",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=LiEMQUIPPQg&t=602",
      reference_angles: null,
      source: "Sunny Lai Wushu — Basic Stances Tutorial",
      sourceUrl: "https://www.youtube.com/watch?v=LiEMQUIPPQg",
      attribution: "community",
    },
  ],
  "fist-palm-hook": [
    {
      id: "fist",
      lesson_id: "fist-palm-hook",
      english: "Fist",
      chinese: "拳",
      pinyin: "Quán",
      description:
        "Fingers curled tightly, thumb pressed over index and middle fingers. Striking surface is the fist face (拳面 quánmiàn).",
      key_points: [
        "Fingers curl tight from pinky inward",
        "Thumb wraps over index and middle knuckles",
        "Wrist straight and locked",
        "Fist face (拳面) is primary striking surface",
        "Back of fist (拳背) for backfist strikes",
      ],
      common_mistakes: [
        "Thumb inside fingers — risk of breaking",
        "Loose fist",
        "Bent wrist on impact",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=oMbb-cZDIeE&t=3",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "palm",
      lesson_id: "fist-palm-hook",
      english: "Palm",
      chinese: "掌",
      pinyin: "Zhǎng",
      description:
        "Fingers extended and pressed together, thumb tucked in. Used for pushing, slicing, and blocking.",
      key_points: [
        "Four fingers straight pressed together",
        "Thumb bent tucked against index base",
        "Wrist bent back (立掌 lìzhǎng) for strikes",
        "Palm base (掌根) is striking surface",
        "Fingers have tension not floppy",
      ],
      common_mistakes: [
        "Fingers spread apart",
        "Thumb sticking out",
        "Floppy wrist",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=oMbb-cZDIeE&t=14",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "hook-hand",
      lesson_id: "fist-palm-hook",
      english: "Hook Hand",
      chinese: "勾手",
      pinyin: "Gōushǒu",
      description:
        "All five fingertips pinched together, wrist bent downward. Used in many traditional and competition forms.",
      key_points: [
        "All five fingertips pinched to a single point",
        "Wrist drops down sharply",
        "Pinched tips point downward",
        "Maintain firm pinch",
        "Arm position varies by technique",
      ],
      common_mistakes: [
        "Fingers not meeting at one point",
        "Wrist not bent enough",
        "Fingers too loose",
      ],
      sort_order: 3,
      video_url: "https://www.youtube.com/watch?v=oMbb-cZDIeE&t=23",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
  "straight-swing-punch": [
    {
      id: "straight-punch",
      lesson_id: "straight-swing-punch",
      english: "Straight Punch",
      chinese: "冲拳",
      pinyin: "Chōngquán",
      description:
        "Most fundamental wushu punch. Fist travels straight from waist to target. Power from waist rotation.",
      key_points: [
        "Fist starts at waist palm up",
        "Fist rotates — palm down at full extension",
        "Elbow stays close to body",
        "Power from waist rotation (拧腰 nǐng yāo)",
        "Non-punching hand pulls back simultaneously",
        "Snap at end don't push",
      ],
      common_mistakes: [
        "Arm-punching forgetting waist rotation",
        "Elbow flaring out",
        "No fist rotation",
        "Shoulders rising",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=2VloZ77iIMY&t=74",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "swinging-punch",
      lesson_id: "straight-swing-punch",
      english: "Swinging Punch",
      chinese: "贯拳",
      pinyin: "Guànquán",
      description:
        "Wide arcing punch targeting temple area. Arm swings in horizontal arc.",
      key_points: [
        "Arm swings in wide horizontal arc",
        "Elbow slightly bent throughout",
        "Back of fist or fist face connects",
        "Target temple height",
        "Waist drives the swing",
        "Often follows straight punch",
      ],
      common_mistakes: [
        "Arm too straight",
        "No body rotation",
        "Dropping other hand",
        "Telegraphing",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=2VloZ77iIMY&t=223",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
  "push-chop-palm": [
    {
      id: "push-palm",
      lesson_id: "push-chop-palm",
      english: "Push Palm",
      chinese: "推掌",
      pinyin: "Tuīzhǎng",
      description:
        "Palm strike pushing forward from the waist or chest. Palm base (掌根) is the contact point.",
      key_points: [
        "Palm pushes forward from waist or chest height",
        "Contact point is palm base (掌根)",
        "Fingers point up wrist bent back",
        "Arm extends fully at completion",
        "Waist and rear leg drive the push",
        "Often used with a forward step",
      ],
      common_mistakes: [
        "Pushing with fingers instead of palm base",
        "No power from lower body",
        "Overreaching and losing balance",
        "Limp wrist",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=2VloZ77iIMY&t=138",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "chop-palm",
      lesson_id: "push-chop-palm",
      english: "Chop / Splitting Palm",
      chinese: "劈掌",
      pinyin: "Pīzhǎng",
      description:
        "Downward chopping palm strike. The outer edge of the palm (掌外沿) slices downward.",
      key_points: [
        "Arm raises above head then chops downward",
        "Outer edge of palm (掌外沿) is contact",
        "Elbow stays slightly bent",
        "Whole body drives the chop downward",
        "Can target collarbone shoulder or forearm",
        "Often paired with a bow stance",
      ],
      common_mistakes: [
        "Chopping with flat palm instead of edge",
        "Only using arm no body",
        "Bending wrist sideways",
        "Not committing to the downward motion",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=2VloZ77iIMY&t=180",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
  "front-side-kick": [
    {
      id: "front-straight-kick",
      lesson_id: "front-side-kick",
      english: "Front Straight Kick",
      chinese: "正踢腿",
      pinyin: "Zhèngtī tuǐ",
      description:
        "Kick leg straight up in front, reaching forehead height or higher. Signature wushu basic kick.",
      key_points: [
        "Kicking leg straight no knee bend",
        "Toes hooked (勾脚) or pointed (绷脚) depending on style",
        "Kick reaches forehead or above",
        "Supporting leg straight and planted",
        "Torso stays upright",
        "Slap foot with opposite hand at peak (明响)",
      ],
      common_mistakes: [
        "Bending kicking leg",
        "Leaning back",
        "Supporting leg bending",
        "Not reaching height",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=jXlALrAfaZY&t=106",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "side-straight-kick",
      lesson_id: "front-side-kick",
      english: "Side Straight Kick",
      chinese: "侧踢腿",
      pinyin: "Cètī tuǐ",
      description:
        "Kick straight up to the side past the ear. Tests lateral flexibility.",
      key_points: [
        "Leg kicks straight up along body side",
        "Reaches past the ear",
        "Torso as upright as possible",
        "Supporting leg straight",
        "Foot hooked or pointed",
        "Opposite hand slaps foot at peak",
      ],
      common_mistakes: [
        "Kicking front-diagonal instead of true side",
        "Excessive torso lean",
        "Bending kicking leg",
        "Rushing instead of controlled",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=jXlALrAfaZY&t=128",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
  "crescent-kicks": [
    {
      id: "outward-crescent",
      lesson_id: "crescent-kicks",
      english: "Outward Crescent Kick",
      chinese: "外摆腿",
      pinyin: "Wàibǎi tuǐ",
      description:
        "Leg swings inside to outside in a crescent arc. Slap foot with opposite hand.",
      key_points: [
        "Leg swings inward first then arcs outward",
        "Path from inside → up → outside",
        "Leg stays straight throughout",
        "Peak at or above head",
        "Opposite hand slaps foot at peak",
        "Control the descent",
      ],
      common_mistakes: [
        "Bending knee during arc",
        "Not enough height",
        "Missing hand slap",
        "No arc just straight kick",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=jXlALrAfaZY&t=168",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "inward-crescent",
      lesson_id: "crescent-kicks",
      english: "Inward Crescent Kick",
      chinese: "里合腿",
      pinyin: "Lǐhé tuǐ",
      description:
        "Leg swings outside to inside in a crescent arc. Reverse of 外摆腿.",
      key_points: [
        "Leg swings outward first then arcs inward",
        "Path from outside → up → inside",
        "Leg stays straight",
        "Peak at or above head",
        "Hand slap at peak",
        "Hip flexibility is key",
      ],
      common_mistakes: [
        "Confusing direction with 外摆腿",
        "Bending leg for height",
        "Too much torso twist",
        "Rushing",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=jXlALrAfaZY&t=199",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
  "snap-thrust-kick": [
    {
      id: "snap-kick",
      lesson_id: "snap-thrust-kick",
      english: "Snap Kick",
      chinese: "弹腿",
      pinyin: "Tántuǐ",
      description:
        "Quick snapping kick using the instep or ball of foot. Knee drives up first, then lower leg snaps out.",
      key_points: [
        "Chamber knee up first (提膝)",
        "Lower leg snaps out from the knee",
        "Contact with instep (脚背) or ball of foot",
        "Kick is fast and retracts quickly",
        "Hip stays stable knee is the hinge",
        "Used for speed strikes to midsection",
      ],
      common_mistakes: [
        "Kicking from the hip instead of snapping from knee",
        "Not chambering first",
        "Slow retraction",
        "Locking knee on impact",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=jXlALrAfaZY&t=235",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "thrust-kick",
      lesson_id: "snap-thrust-kick",
      english: "Thrust / Stomp Kick",
      chinese: "蹬腿",
      pinyin: "Dēngtuǐ",
      description:
        "Heel-first pushing kick. Knee chambers up, then foot thrusts forward with heel as contact.",
      key_points: [
        "Chamber knee up first",
        "Thrust forward with heel (脚跟) as contact",
        "Toes pulled back to expose heel",
        "Push through the target",
        "Hips drive the thrust forward",
        "Used to push opponent back or strike midsection",
      ],
      common_mistakes: [
        "Kicking with toes instead of heel",
        "No hip drive",
        "Not chambering properly",
        "Leaning back too much",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=jXlALrAfaZY&t=242",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
  "knee-swallow-balance": [
    {
      id: "knee-lift-balance",
      lesson_id: "knee-swallow-balance",
      english: "Knee Lift Balance",
      chinese: "提膝平衡",
      pinyin: "Tíxī pínghéng",
      description:
        "Stand on one leg, other knee raised high. Most basic balance position.",
      key_points: [
        "Supporting leg straight and locked",
        "Knee lifts above waist height",
        "Raised toes pointed down (绷脚)",
        "Torso upright chest open",
        "Hold 2+ seconds in competition",
        "Focus eyes on fixed point",
      ],
      common_mistakes: [
        "Supporting leg bending",
        "Knee not high enough",
        "Wobbling",
        "Hunching forward",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=W9HS4-f_NGo&t=38",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "swallow-balance",
      lesson_id: "knee-swallow-balance",
      english: "Swallow Balance",
      chinese: "燕式平衡",
      pinyin: "Yànshì pínghéng",
      description:
        "Stand on one leg, torso forward, back leg extended behind — T-shape.",
      key_points: [
        "Supporting leg straight",
        "Torso parallel to ground",
        "Back leg extends straight behind parallel",
        "Arms spread wide or designated position",
        "Head up looking forward",
        "T-shape from side view",
      ],
      common_mistakes: [
        "Back leg not high enough",
        "Supporting leg bending",
        "Head dropping",
        "Excessive back arch",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=W9HS4-f_NGo&t=41",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
  "flexibility-foundations": [
    {
      id: "front-leg-press",
      lesson_id: "flexibility-foundations",
      english: "Front Leg Press",
      chinese: "正压腿",
      pinyin: "Zhèng yā tuǐ",
      description:
        "Front leg stretch on a bar or elevated surface. Fundamental flexibility exercise for all kicks.",
      key_points: [
        "Place heel on bar at hip height or higher",
        "Standing leg straight",
        "Lean torso forward over the raised leg",
        "Keep back straight not rounded",
        "Hold 30-60 seconds each side",
        "Breathe and relax into stretch progressively",
      ],
      common_mistakes: [
        "Rounding the back to reach further",
        "Bending standing leg",
        "Bouncing instead of holding",
        "Raising hip on the stretching side",
      ],
      sort_order: 1,
      video_url: "https://www.youtube.com/watch?v=dD_uEePnT7M&t=431",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "side-leg-press",
      lesson_id: "flexibility-foundations",
      english: "Side Leg Press",
      chinese: "侧压腿",
      pinyin: "Cè yā tuǐ",
      description:
        "Side leg stretch with leg on a bar. Essential for side kicks and crescent kicks.",
      key_points: [
        "Stand sideways to bar",
        "Place heel on bar to the side",
        "Lean torso sideways toward raised foot",
        "Keep both legs straight",
        "Hips face forward",
        "Hold 30-60 seconds",
      ],
      common_mistakes: [
        "Hips rotating instead of facing forward",
        "Bending either leg",
        "Not going deep enough",
        "Leaning forward instead of sideways",
      ],
      sort_order: 2,
      video_url: "https://www.youtube.com/watch?v=dD_uEePnT7M&t=530",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
    {
      id: "front-split",
      lesson_id: "flexibility-foundations",
      english: "Front Split",
      chinese: "竖叉",
      pinyin: "Shù chā",
      description:
        "Full front split — ultimate flexibility goal for wushu. Requires months of progressive training.",
      key_points: [
        "Front leg straight with heel on ground",
        "Back leg straight behind hip open",
        "Hips square and level",
        "Torso upright",
        "Use blocks/pillows for support as needed",
        "Train daily with progressive depth",
      ],
      common_mistakes: [
        "Back leg rotated outward (hip not open)",
        "Hips not squared",
        "Forcing depth before ready",
        "Skipping warm up",
      ],
      sort_order: 3,
      video_url: "https://www.youtube.com/watch?v=dD_uEePnT7M&t=413",
      reference_angles: null,
      source: null,
      attribution: "unattributed",
      sourceNotes: "Video source unverified — content is standard wushu terminology",
    },
  ],
};

// ─── Quiz data ─────────────────────────────────────────────────────────────
function q(
  id: string,
  lessonId: string,
  sort: number,
  question: string,
  options: string[],
  correctIndex: number,
): QuizQuestion {
  return {
    id,
    lesson_id: lessonId,
    question,
    options,
    correct_index: correctIndex,
    explanation: null,
    sort_order: sort,
  };
}

export const DEMO_QUIZZES: Record<string, QuizQuestion[]> = {
  "horse-bow-stance": [
    q("hb-1", "horse-bow-stance", 1, "At what angle should the knees bend in 马步 (Horse Stance)?", ["45°", "60°", "90°", "120°"], 2),
    q("hb-2", "horse-bow-stance", 2, "In 弓步 (Bow Stance), where should the front knee be?", ["Past the toes", "Directly above the ankle", "Behind the heel", "Fully straight"], 1),
    q("hb-3", "horse-bow-stance", 3, "In Horse Stance, weight distribution should be:", ["70% front / 30% rear", "100% rear leg", "Evenly balanced on both feet", "On the toes"], 2),
    q("hb-4", "horse-bow-stance", 4, "What does 马步 (mǎbù) literally mean?", ["Bow step", "Horse stance/step", "Empty stance", "Rest stance"], 1),
  ],
  "empty-crouch-stance": [
    q("ec-1", "empty-crouch-stance", 1, "What percent of weight sits on the rear leg in 虚步?", ["50%", "70%", "~90%", "100%"], 2),
    q("ec-2", "empty-crouch-stance", 2, "In 仆步 (Crouch Stance), the extended leg must be:", ["Slightly bent", "Completely straight", "Lifted off the floor", "Rolled onto outer edge"], 1),
    q("ec-3", "empty-crouch-stance", 3, "What does 虚 (xū) mean?", ["Full", "Empty", "Strong", "Low"], 1),
    q("ec-4", "empty-crouch-stance", 4, "A common mistake in 虚步 is:", ["Leaning the torso backward", "Keeping the spine vertical", "Bending the rear knee", "Lifting the front heel"], 0),
  ],
  "cross-stance": [
    q("cs-1", "cross-stance", 1, "In 歇步, both feet should be:", ["On the toes", "Flat on the ground", "Lifted", "Rolled outward"], 1),
    q("cs-2", "cross-stance", 2, "What does 歇 (xiē) mean?", ["Cross", "Rest", "Jump", "Spin"], 1),
    q("cs-3", "cross-stance", 3, "The rear knee in 歇步 should:", ["Stay high", "Hover just above the floor", "Rest on the ground", "Point outward"], 1),
    q("cs-4", "cross-stance", 4, "歇步 is most often used before:", ["Slow walking", "Explosive jumps and turns", "High kicks", "Standing still"], 1),
  ],
  "fist-palm-hook": [
    q("fph-1", "fist-palm-hook", 1, "What is the Chinese word for fist?", ["掌 zhǎng", "拳 quán", "勾 gōu", "爪 zhǎo"], 1),
    q("fph-2", "fist-palm-hook", 2, "In 掌, where should the thumb be?", ["Extended outward", "Inside fingers", "Tucked against index finger base", "Pointing up"], 2),
    q("fph-3", "fist-palm-hook", 3, "What does 勾手 look like?", ["Open palm", "Closed fist", "Fingertips pinched, wrist dropped", "Two fingers extended"], 2),
    q("fph-4", "fist-palm-hook", 4, "What is 拳面 (quánmiàn)?", ["Back of fist", "Face/front of fist", "Side of fist", "Bottom of fist"], 1),
  ],
  "straight-swing-punch": [
    q("ssp-1", "straight-swing-punch", 1, "What does 冲 (chōng) mean?", ["Swing", "Thrust/Rush", "Block", "Hook"], 1),
    q("ssp-2", "straight-swing-punch", 2, "Where does the fist start in 冲拳?", ["Beside ear", "At waist, palm up", "In front of chest", "Behind back"], 1),
    q("ssp-3", "straight-swing-punch", 3, "What generates power in 冲拳?", ["Shoulder strength", "Waist rotation (拧腰)", "Jumping", "Arm speed only"], 1),
    q("ssp-4", "straight-swing-punch", 4, "What is 贯拳?", ["Uppercut", "Straight punch", "Swinging / hooking punch", "Backfist"], 2),
  ],
  "push-chop-palm": [
    q("pcp-1", "push-chop-palm", 1, "What does 推 (tuī) mean?", ["Chop", "Push", "Slap", "Pull"], 1),
    q("pcp-2", "push-chop-palm", 2, "Contact point in 推掌 is?", ["Fingertips", "Fist", "Palm base (掌根)", "Back of hand"], 2),
    q("pcp-3", "push-chop-palm", 3, "What direction does 劈掌 go?", ["Upward", "Sideways", "Downward chop", "Forward thrust"], 2),
    q("pcp-4", "push-chop-palm", 4, "What is 掌外沿?", ["Palm base", "Fingertips", "Outer edge of palm", "Center of palm"], 2),
  ],
  "front-side-kick": [
    q("fsk-1", "front-side-kick", 1, "What does 正踢腿 mean?", ["Side kick", "Front straight kick", "Crescent kick", "Spin kick"], 1),
    q("fsk-2", "front-side-kick", 2, "What is 勾脚 (gōu jiǎo)?", ["Pointed toes", "Hooked / flexed foot", "Relaxed foot", "Turned-in toes"], 1),
    q("fsk-3", "front-side-kick", 3, "Supporting leg in 正踢腿 should?", ["Bend for balance", "Stay straight and planted", "Hop slightly", "Turn outward"], 1),
    q("fsk-4", "front-side-kick", 4, "What does 侧 (cè) mean?", ["Front", "Back", "Side", "Spin"], 2),
  ],
  "crescent-kicks": [
    q("ck-1", "crescent-kicks", 1, "Direction of 外摆腿?", ["Inside to outside", "Outside to inside", "Straight up", "Straight back"], 0),
    q("ck-2", "crescent-kicks", 2, "What does 里 (lǐ) mean?", ["Outside", "Inside / Inward", "Straight", "Spinning"], 1),
    q("ck-3", "crescent-kicks", 3, "Kick path shape?", ["Straight line", "Circle", "Crescent arc", "Zigzag"], 2),
    q("ck-4", "crescent-kicks", 4, "外 means _____, 里 means _____", ["Up / Down", "Left / Right", "Outside / Inside", "Fast / Slow"], 2),
  ],
  "snap-thrust-kick": [
    q("stk-1", "snap-thrust-kick", 1, "What makes 弹腿 different from straight kicks?", ["Height", "Snapping motion from the knee", "Direction", "Speed only"], 1),
    q("stk-2", "snap-thrust-kick", 2, "Contact point for 蹬腿?", ["Toes", "Ball of foot", "Heel (脚跟)", "Instep"], 2),
    q("stk-3", "snap-thrust-kick", 3, "What does 弹 (tán) mean?", ["Thrust", "Snap / spring", "Sweep", "Hook"], 1),
    q("stk-4", "snap-thrust-kick", 4, "Both 弹腿 and 蹬腿 start by?", ["Jumping", "Spinning", "Chambering the knee up", "Leaning back"], 2),
  ],
  "knee-swallow-balance": [
    q("ksb-1", "knee-swallow-balance", 1, "What does 燕 (yàn) mean?", ["Eagle", "Swallow bird", "Crane", "Phoenix"], 1),
    q("ksb-2", "knee-swallow-balance", 2, "Shape of 燕式平衡 from the side?", ["L-shape", "V-shape", "T-shape", "S-shape"], 2),
    q("ksb-3", "knee-swallow-balance", 3, "What does 平衡 (pínghéng) mean?", ["Kick", "Stance", "Balance", "Jump"], 2),
    q("ksb-4", "knee-swallow-balance", 4, "Knee height in 提膝平衡?", ["Ankle", "Below waist", "Above waist", "Shoulder"], 2),
  ],
  "flexibility-foundations": [
    q("ff-1", "flexibility-foundations", 1, "What does 柔韧 (róurèn) mean?", ["Strength", "Flexibility", "Speed", "Endurance"], 1),
    q("ff-2", "flexibility-foundations", 2, "In 正压腿, the back should be?", ["Rounded", "Twisted", "Straight", "Arched back"], 2),
    q("ff-3", "flexibility-foundations", 3, "竖叉 is?", ["Side split", "Front split", "Backbend", "Handstand"], 1),
    q("ff-4", "flexibility-foundations", 4, "Best approach to flexibility?", ["Bounce hard", "Force it fast", "Daily progressive stretching", "Once a week deep push"], 2),
  ],
};
