import type { StanceCheckConfig } from "./types";

/**
 * MediaPipe Pose landmark indices:
 *   11 left shoulder   12 right shoulder
 *   23 left hip        24 right hip
 *   25 left knee       26 right knee
 *   27 left ankle      28 right ankle
 *   31 left foot index 32 right foot index
 *
 * Convention: "front view" = user facing camera; "side view" = user rotated 90°.
 * "Front leg" / "back leg" for asymmetric stances assumes the left side is forward.
 * Mirror-image evaluation is not attempted — instruct users to face the same way each time.
 */

export const STANCE_CHECKS: Record<string, StanceCheckConfig> = {
  // ============================================================
  // 马步 MABU — Horse Stance
  // Primary view: front
  // ============================================================
  "horse-stance": {
    techniqueId: "horse-stance",
    primaryView: "front",
    checks: [
      {
        id: "mabu-width",
        label: "Stance width",
        kind: "ratio",
        view: "front",
        severity: "major",
        numerator: [27, 28],
        denominator: [11, 12],
        dimension: "x",
        target: 2.0,
        tolerance: 0.2,
        targetLabel: "2× shoulder (1.8–2.2)",
        messageLow: "Stance too narrow — widen to 2× shoulder width",
        messageHigh: "Stance too wide — bring feet slightly in",
      },
      {
        id: "mabu-left-knee",
        label: "Left knee angle",
        kind: "angle",
        view: "side",
        severity: "major",
        landmarks: [23, 25, 27],
        target: 90,
        tolerance: 12,
        targetLabel: "90° ±12°",
        messageLow: "Don't over-bend — keep thighs parallel",
        messageHigh: "Sink lower — thighs should be parallel to floor",
      },
      {
        id: "mabu-right-knee",
        label: "Right knee angle",
        kind: "angle",
        view: "side",
        severity: "major",
        landmarks: [24, 26, 28],
        target: 90,
        tolerance: 12,
        targetLabel: "90° ±12°",
        messageLow: "Don't over-bend — keep thighs parallel",
        messageHigh: "Sink lower — thighs should be parallel to floor",
      },
      {
        id: "mabu-knee-symmetry",
        label: "Knee symmetry",
        kind: "symmetry",
        view: "front",
        severity: "minor",
        angleA: [23, 25, 27],
        angleB: [24, 26, 28],
        tolerance: 5,
        targetLabel: "within 5°",
        message: "Uneven weight — knees at different heights",
      },
      {
        id: "mabu-thigh-parallel",
        label: "Thigh parallel",
        kind: "alignment",
        view: "side",
        severity: "major",
        axis: "y",
        a: 23,
        b: 25,
        tolerance: 0.05,
        comparator: "abs",
        targetLabel: "hip ≈ knee height",
        messageLow: "Sink lower — thighs not parallel to floor",
        messageHigh: "Sink lower — thighs not parallel to floor",
      },
      {
        id: "mabu-torso",
        label: "Torso vertical",
        kind: "torsoLean",
        view: "side",
        severity: "minor",
        target: 0,
        tolerance: 8,
        targetLabel: "0° ±8°",
        messageLow: "Leaning forward — straighten your back",
        messageHigh: "Leaning back — straighten your torso",
      },
      {
        id: "mabu-left-foot-forward",
        label: "Left foot forward",
        kind: "footAngle",
        view: "front",
        severity: "minor",
        ankle: 27,
        foot: 31,
        target: 90,
        tolerance: 15,
        targetLabel: "toes toward camera ±15°",
        message: "Toes pointing out — rotate feet forward",
      },
      {
        id: "mabu-right-foot-forward",
        label: "Right foot forward",
        kind: "footAngle",
        view: "front",
        severity: "minor",
        ankle: 28,
        foot: 32,
        target: 90,
        tolerance: 15,
        targetLabel: "toes toward camera ±15°",
        message: "Toes pointing out — rotate feet forward",
      },
      {
        id: "mabu-left-knee-track",
        label: "Left knee over ankle",
        kind: "alignment",
        view: "front",
        severity: "major",
        axis: "x",
        a: 25,
        b: 27,
        tolerance: 0.04,
        comparator: "abs",
        targetLabel: "knee above ankle",
        message: "Knees caving inward — push them out over your toes",
      },
      {
        id: "mabu-right-knee-track",
        label: "Right knee over ankle",
        kind: "alignment",
        view: "front",
        severity: "major",
        axis: "x",
        a: 26,
        b: 28,
        tolerance: 0.04,
        comparator: "abs",
        targetLabel: "knee above ankle",
        message: "Knees caving inward — push them out over your toes",
      },
    ],
  },

  // ============================================================
  // 弓步 GONGBU — Bow Stance
  // Primary view: side
  // Convention: left leg forward
  // ============================================================
  "bow-stance": {
    techniqueId: "bow-stance",
    primaryView: "side",
    checks: [
      {
        id: "gongbu-front-knee",
        label: "Front knee angle",
        kind: "angle",
        view: "side",
        severity: "major",
        landmarks: [23, 25, 27],
        target: 90,
        tolerance: 12,
        targetLabel: "90° ±12°",
        messageLow: "Bend front knee more — target 90°",
        messageHigh: "Sink deeper into the bow",
      },
      {
        id: "gongbu-knee-not-past-toes",
        label: "Knee over ankle",
        kind: "alignment",
        view: "side",
        severity: "critical",
        axis: "x",
        a: 25,
        b: 27,
        tolerance: 0.04,
        comparator: "leq",
        targetLabel: "knee x ≤ ankle x",
        message: "Front knee past toes — pull knee back over ankle",
      },
      {
        id: "gongbu-back-leg",
        label: "Back leg straight",
        kind: "angle",
        view: "side",
        severity: "major",
        landmarks: [24, 26, 28],
        target: 175,
        tolerance: 12,
        targetLabel: "165–180°",
        messageLow: "Straighten your back leg completely",
        messageHigh: "Back leg is fine",
      },
      {
        id: "gongbu-back-foot-angle",
        label: "Back foot angle",
        kind: "footAngle",
        view: "front",
        severity: "minor",
        ankle: 28,
        foot: 32,
        target: 45,
        tolerance: 15,
        targetLabel: "45° out (30–50°)",
        message: "Back foot should be angled out ~45°",
      },
      {
        id: "gongbu-hips-squared",
        label: "Hips squared",
        kind: "ratio",
        view: "front",
        severity: "minor",
        numerator: [23, 24],
        denominator: [11, 12],
        dimension: "x",
        target: 1.0,
        tolerance: 0.2,
        targetLabel: "hips ≈ shoulders",
        message: "Square your hips forward",
      },
      {
        id: "gongbu-torso",
        label: "Torso upright",
        kind: "torsoLean",
        view: "side",
        severity: "minor",
        target: 0,
        tolerance: 8,
        targetLabel: "0° ±8°",
        messageLow: "Leaning too far forward",
        messageHigh: "Leaning too far back",
      },
    ],
  },

  // ============================================================
  // 仆步 PUBU — Crouch Stance
  // Primary view: side
  // Convention: bent leg is left (near camera), extended leg is right
  // ============================================================
  "crouch-stance": {
    techniqueId: "crouch-stance",
    primaryView: "side",
    checks: [
      {
        id: "pubu-bent-knee",
        label: "Bent knee depth",
        kind: "angle",
        view: "side",
        severity: "major",
        landmarks: [23, 25, 27],
        target: 40,
        tolerance: 12,
        targetLabel: "≤52°",
        messageLow: "Bent knee is fine",
        messageHigh: "Not deep enough — bent leg should be fully flexed",
      },
      {
        id: "pubu-extended-leg",
        label: "Extended leg straight",
        kind: "angle",
        view: "side",
        severity: "major",
        landmarks: [24, 26, 28],
        target: 175,
        tolerance: 12,
        targetLabel: "165–180°",
        messageLow: "Straighten your extended leg fully",
        messageHigh: "Extended leg is fine",
      },
      {
        id: "pubu-hip-depth",
        label: "Hip at knee level",
        kind: "alignment",
        view: "side",
        severity: "major",
        axis: "y",
        a: 23,
        b: 25,
        tolerance: 0.03,
        comparator: "geq",
        targetLabel: "hip ≥ knee depth",
        message: "Sink deeper — hip should be at knee level",
      },
      {
        id: "pubu-heel-down",
        label: "Extended heel down",
        kind: "alignment",
        view: "side",
        severity: "minor",
        axis: "y",
        a: 28,
        b: 32,
        tolerance: 0.03,
        comparator: "abs",
        targetLabel: "ankle ≈ toe height",
        message: "Extended foot lifted — keep heel on ground",
      },
      {
        id: "pubu-torso",
        label: "Torso upright",
        kind: "torsoLean",
        view: "side",
        severity: "minor",
        target: 0,
        tolerance: 8,
        targetLabel: "0° ±8°",
        messageLow: "Leaning too far forward",
        messageHigh: "Leaning too far back",
      },
    ],
  },

  // ============================================================
  // 虚步 XUBU — Empty Stance
  // Primary view: side
  // Convention: weight on back leg (right/far from camera), front leg (left) empty
  // ============================================================
  "empty-stance": {
    techniqueId: "empty-stance",
    primaryView: "side",
    checks: [
      {
        id: "xubu-back-knee",
        label: "Back knee bend",
        kind: "angle",
        view: "side",
        severity: "major",
        landmarks: [24, 26, 28],
        target: 100,
        tolerance: 12,
        targetLabel: "88–112°",
        messageLow: "Standing too tall — bend back knee more",
        messageHigh: "Sit lower on the back leg",
      },
      {
        id: "xubu-weight-back",
        label: "Weight on back leg",
        kind: "alignment",
        view: "side",
        severity: "major",
        axis: "y",
        a: 24,
        b: 23,
        tolerance: 0.02,
        comparator: "geq",
        targetLabel: "back hip lower than front hip",
        message: "Too much weight on front foot — it should be empty",
      },
      {
        id: "xubu-front-knee",
        label: "Front knee slight bend",
        kind: "angle",
        view: "side",
        severity: "minor",
        landmarks: [23, 25, 27],
        target: 160,
        tolerance: 12,
        targetLabel: "148–172°",
        messageLow: "Front knee too bent",
        messageHigh: "Front knee too straight",
      },
      {
        id: "xubu-heel-up",
        label: "Front heel lifted",
        kind: "alignment",
        view: "side",
        severity: "minor",
        axis: "y",
        a: 31,
        b: 27,
        tolerance: 0.02,
        comparator: "leq",
        targetLabel: "toe below ankle (heel up)",
        message: "Front foot should be on toes only, heel up",
      },
      {
        id: "xubu-torso",
        label: "Torso upright",
        kind: "torsoLean",
        view: "side",
        severity: "minor",
        target: 0,
        tolerance: 8,
        targetLabel: "0° ±8°",
        messageLow: "Leaning forward — sit back into the stance",
        messageHigh: "Leaning back too far",
      },
    ],
  },

  // ============================================================
  // 歇步 XIEBU — Rest Stance
  // Primary view: front
  // ============================================================
  "rest-stance": {
    techniqueId: "rest-stance",
    primaryView: "front",
    checks: [
      {
        id: "xiebu-crossed",
        label: "Legs crossed",
        kind: "legsCrossed",
        view: "front",
        severity: "critical",
        targetLabel: "ankles inverted vs hips",
        message: "Cross your legs — back leg behind the front",
      },
      {
        id: "xiebu-front-depth",
        label: "Front knee depth",
        kind: "angle",
        view: "front",
        severity: "major",
        landmarks: [23, 25, 27],
        target: 50,
        tolerance: 12,
        targetLabel: "≤62°",
        messageLow: "Front knee fine",
        messageHigh: "Sink lower — deeper squat",
      },
      {
        id: "xiebu-back-depth",
        label: "Back knee depth",
        kind: "angle",
        view: "front",
        severity: "major",
        landmarks: [24, 26, 28],
        target: 50,
        tolerance: 12,
        targetLabel: "≤62°",
        messageLow: "Back knee fine",
        messageHigh: "Sink lower — deeper squat",
      },
      {
        id: "xiebu-hip-low",
        label: "Hip low",
        kind: "alignment",
        view: "front",
        severity: "major",
        axis: "y",
        a: 23,
        b: 25,
        tolerance: 0.05,
        comparator: "geq",
        targetLabel: "hip near knee height",
        message: "Sink lower — deeper squat",
      },
      {
        id: "xiebu-back-heel-up",
        label: "Back heel lifted",
        kind: "alignment",
        view: "front",
        severity: "minor",
        axis: "y",
        a: 32,
        b: 28,
        tolerance: 0.02,
        comparator: "leq",
        targetLabel: "toe below ankle (heel up)",
        message: "Back heel should be lifted, only ball touches",
      },
      {
        id: "xiebu-torso",
        label: "Torso upright",
        kind: "torsoLean",
        view: "front",
        severity: "minor",
        target: 0,
        tolerance: 8,
        targetLabel: "0° ±8°",
        messageLow: "Leaning forward — stay upright",
        messageHigh: "Leaning back too far",
      },
    ],
  },
};

export function getStanceConfig(techniqueId: string): StanceCheckConfig | null {
  return STANCE_CHECKS[techniqueId] ?? null;
}
